// app/layout.jsx
import "./globals.css";
import Header from "../components/Header";

export const metadata = {
  title: "My Portfolio",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
